version: '3.9'
services:
  database:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_PASSWORD: 1357924680h
      POSTGRES_USER: postgres
      POSTGRES_DB: tools3
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://postgres:1357924680h@database:5432/tools3
    depends_on:
      - database
    ports:
      - 3001:3001

  frontend:
    build:
      context: ./front-end/app
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:80

volumes:
  db-data:
