version: '27'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1357924680h
      POSTGRES_USER: postgres
      POSTGRES_DB: tools3
  app:
    image: my-app
    ports:
      - 13000:3001
